### ISSUE TITLE
Panic in DepGraph::render_to

### ISSUE THREAD

**Issue by bluss** [kbknapp/cargo-graph#18]
Follow up on #15. Graph with deps look nice. Without dev-deps, it panics:

Node N14 doesn't exist, but it tries to add the edge N3 -> N14. N3 is memchr so the only thing it should link to is `libc`.

```
$ RUST_BACKTRACE=1 ~/bin/cargo-graph graph 
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
stack backtrace:
   1:     0x5599470a91a0 - sys::backtrace::tracing::imp::write::h2121cc3fd481a5bfxXt
   2:     0x5599470ab565 - panicking::log_panic::_<closure>::closure.41181
   3:     0x5599470aafe0 - panicking::log_panic::h274f0982d2d31f5d62x
   4:     0x55994709ed93 - sys_common::unwind::begin_unwind_inner::ha197e3d3bf39738b4Ps
   5:     0x55994709f128 - sys_common::unwind::begin_unwind_fmt::h377d567d53530218aPs
   6:     0x5599470a8801 - rust_begin_unwind
   7:     0x5599470d7d6f - panicking::panic_fmt::hd08c5b6fdb7b10daxuL
   8:     0x5599470d8048 - panicking::panic::h588d88296fb1b1954sL
   9:     0x559946f4f942 - option::_<impl>::unwrap::unwrap::h16263530560132818147
                        at ../src/libcore/macros.rs:20
  10:     0x559946f4ee67 - graph::_<impl>::label::h10115180723912119468
                        at src/graph.rs:17
  11:     0x559946f490ff - graph::_<impl>::render_to::h7564755762930757336
                        at src/graph.rs:142
  12:     0x559946f43159 - execute::h2d7033028e348fb8ogc
                        at src/main.rs:390
  13:     0x559946f3d2ed - main::h75e0a80141ee56f0Ifc
                        at src/main.rs:378
  14:     0x5599470aad84 - sys_common::unwind::try::try_fn::h1190371136003024825
  15:     0x5599470a8648 - __rust_try
  16:     0x5599470aaa26 - rt::lang_start::h63ca0c2ab43f095fe0x
  17:     0x559946f43399 - main
  18:     0x7f94da5bdb44 - __libc_start_main
  19:     0x559946f30c38 - <unknown>
  20:                0x0 - <unknown>
digraph dependencies {
        N0[label="twoway"];
        N1[label="itertools"];
        N2[label="jetscii"];
        N3[label="memchr"];
        N4[label="odds"];
        N5[label="quickcheck"];
        N6[label="rand"];
        N7[label="advapi32-sys"];
        N8[label="winapi"];
        N9[label="winapi-build"];
        N10[label="libc"];
        N11[label="log"];
        N12[label="unreachable"];
        N13[label="void"];
        N0 -> N1[label=""];
        N0 -> N2[label=""];
        N0 -> N3[label=""];
        N0 -> N4[label=""];
        N0 -> N5[label=""];
        N0 -> N6[label=""];
        N0 -> N7[label=""];
        N0 -> N8[label=""];
        N0 -> N9[label=""];
        N3 -> N14

```

**Comment by kbknapp** [comment]
Thanks for the report! I'll look into and report back :+1:

**Comment by kbknapp** [comment]
@bluss #18 should take care of this!
