### ISSUE TITLE
Error when running `cargo graph`

### ISSUE THREAD

**Issue by bvssvni** [kbknapp/cargo-graph#5]
```
<stdin>:1:2: 1:3 error: unknown start of token: \\
<stdin>:1 C\:> setx path \"%path%;C:\path\to\cargo-graph\binary\"
           ^
thread '<unnamed>' panicked at 'Box<Any>', ../src/libsyntax/parse/lexer/mod.rs:1227
Could not document `cargo-graph`.
```

**Comment by kbknapp** [comment]
So as not to be confused with the original project (should the repo become picked up again) I renamed this project to `cargo-graph` so after a `cargo install cargo-graph` once in a repository you'd run `cargo graph [option]` not `cargo dot`

If this error was reached using `cargo graph` I'll need to investigate because the line you ref in the error message is no longer in this repo, so perhaps it's an older version that was cloned?

**Comment by bvssvni** [comment]
Sorry, meant `cargo graph`. I'll check and reopen if it is still a problem.

**Comment by kbknapp** [comment]
Ah ok, no worries. Yeah that was a problem, but shouldve been fixed already, so let me know if it pops back up!

**Comment by bvssvni** [comment]
```
$ cargo doc --verbose
       Fresh strsim v0.4.0
       Fresh bitflags v0.3.2
       Fresh vec_map v0.4.0
       Fresh rustc-serialize v0.3.16
       Fresh ansi_term v0.7.0
       Fresh toml v0.1.23
       Fresh clap v1.5.2
 Documenting cargo-graph v0.1.3 (file:///Users/sven/rust/cargo-graph)
     Running `rustdoc src/main.rs --crate-name cargo_graph -o /Users/sven/rust/cargo-graph/target/doc --cfg feature=\"color\" --cfg feature=\"default\" --cfg feature=\"ansi_term\" -L dependency=/Users/sven/rust/cargo-graph/target/debug -L dependency=/Users/sven/rust/cargo-graph/target/debug/deps --extern clap=/Users/sven/rust/cargo-graph/target/debug/deps/libclap-e5fbbb239d77fa50.rlib --extern clap=/Users/sven/rust/cargo-graph/target/debug/deps/libclap-e5fbbb239d77fa50.rlib --extern ansi_term=/Users/sven/rust/cargo-graph/target/debug/deps/libansi_term-9d420728129b78bf.rlib --extern ansi_term=/Users/sven/rust/cargo-graph/target/debug/deps/libansi_term-9d420728129b78bf.rlib --extern toml=/Users/sven/rust/cargo-graph/target/debug/deps/libtoml-7d16d978f944b9c6.rlib --extern toml=/Users/sven/rust/cargo-graph/target/debug/deps/libtoml-7d16d978f944b9c6.rlib`
<stdin>:1:2: 1:3 error: unknown start of token: \\
<stdin>:1 C\:> setx path \"%path%;C:\path\to\cargo-graph\binary\"
           ^
thread '<unnamed>' panicked at 'Box<Any>', ../src/libsyntax/parse/lexer/mod.rs:1227
Could not document `cargo-graph`.

Caused by:
  Process didn't exit successfully: `rustdoc src/main.rs --crate-name cargo_graph -o /Users/sven/rust/cargo-graph/target/doc --cfg feature="color" --cfg feature="default" --cfg feature="ansi_term" -L dependency=/Users/sven/rust/cargo-graph/target/debug -L dependency=/Users/sven/rust/cargo-graph/target/debug/deps --extern clap=/Users/sven/rust/cargo-graph/target/debug/deps/libclap-e5fbbb239d77fa50.rlib --extern clap=/Users/sven/rust/cargo-graph/target/debug/deps/libclap-e5fbbb239d77fa50.rlib --extern ansi_term=/Users/sven/rust/cargo-graph/target/debug/deps/libansi_term-9d420728129b78bf.rlib --extern ansi_term=/Users/sven/rust/cargo-graph/target/debug/deps/libansi_term-9d420728129b78bf.rlib --extern toml=/Users/sven/rust/cargo-graph/target/debug/deps/libtoml-7d16d978f944b9c6.rlib --extern toml=/Users/sven/rust/cargo-graph/target/debug/deps/libtoml-7d16d978f944b9c6.rlib` (exit code: 101)
```

**Comment by bvssvni** [comment]
@kbknapp I can't reopen the issue.

**Comment by kbknapp** [comment]
Ok yeah, this the same issue as before. I'll just remove that portion of the crate docs.

**Comment by kbknapp** [comment]
#12 should take care of this :wink:

**Comment by bvssvni** [comment]
Nice!

**Comment by kbknapp** [comment]
0.1.4 is up on crates.io now for `cargo install`, or you can use master here.
